name: quiver
version: 0.9.1
authors:
- Justin Fagnani <justinfagnani@google.com>
- Yegor Jbanov <yjbanov@google.com>
- Chris Bracken <cbracken@google.com>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A set of utility libraries for Dart
homepage: https://github.com/google/quiver-dart
documentation: http://google.github.io/quiver-dart/docs/
environment:
  sdk: '>=0.7.2 <0.8.0'
dependencies:
  path: '>=0.7.2 <0.8.0'
dev_dependencies:
  unittest: '>=0.7.2 <0.8.0'
