name: quiver
version: 0.21.3
authors:
- Justin Fagnani <justinfagnani@google.com>
- Yegor Jbanov <yjbanov@google.com>
- Chris Bracken <cbracken@google.com>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
- David Morgan <davidmorgan@google.com>
- John McDole <codefu@google.com>
- Matan Lurey <matanl@google.com>
description: A set of utility libraries for Dart
homepage: https://github.com/google/quiver-dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  matcher: '>=0.10.0 <0.12.0'
dev_dependencies:
  path: '>=1.0.0 <2.0.0'
  unittest: '>=0.11.0'
